backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Featured Post", name: "featuredpost", widget: "boolean", required: false }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - { label: "House Type", name: "housetype", widget: "string", required: false }
      - { label: "State", name: "state", widget: "string", required: false }
      - { label: "Land Size", name: "landsize", widget: "string", required: false }
      - { label: "Year of Build", name: "yearofbuild", widget: "string", required: false }
      - { label: "Purchased Date", name: "purchaseddate", widget: "string", required: false }
      - { label: "Purchased Price", name: "purchasedprice", widget: "string", required: false }
      - { label: "Bank Desktop Value", name: "bankdesktopvalue", widget: "string", required: false }
      - { label: "Current Rent", name: "currentrent", widget: "string", required: false }
      - { label: "Key point", name: "keypoint", widget: "string" }


  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Image, name: image, widget: image }
          - { label: Agent, name: agent, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Subheading, name: subheading, widget: string }
          - {
              label: Mainpitch,
              name: mainpitch,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: text },
                ],
            }
          - {
              label: Testimonials,
              name: testimonials,
              widget: list,
              fields:
                [
                  { label: Author, name: author_name, widget: string },
                  { label: Quote, name: text, widget: string },
                  { label: Photo, name: profile_photo_url, widget: string },
                  { rating: Rating, name: rating, widget: number },
                  { label: Time, name: relative_time_description, widget: string },
                ],
            }
          - {
              label: Social Media,
              name: socialmedia,
              widget: list,
              fields:
                [
                  { label: Name, name: name, widget: string },
                  { label: Link, name: link, widget: string },
                  { label: QR, name: qr, widget: image },
                ],
            }
      - file: "src/pages/services/index.md"
        label: "Services"
        name: "services"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "services-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
  - name: "cn"
    label: "中文頁面"
    files:
      - file: "src/pages/cn/index.md"
        label: "首頁"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: 背景圖, name: image, widget: image }
          - { label: BA照片, name: agent, widget: image }
          - { label: 標題, name: heading, widget: string }
          - { label: 副標題, name: subheading, widget: string }
          - {
              label: 白色背景,
              name: mainpitch,
              widget: object,
              fields:
                [
                  { label: 白色背景標題, name: title, widget: string },
                  { label: 白色背景副標題, name: description, widget: text },
                ],
            }
          - {
              label: 好評,
              name: testimonials,
              widget: list,
              fields:
                [
                  { label: 提交者, name: author_name, widget: string },
                  { label: 內容, name: text, widget: string },
                  { label: 提交者照片, name: profile_photo_url, widget: string },
                  { rating: 評星, name: rating, widget: number },
                  { label: 時間, name: relative_time_description, widget: string },
                ],
            }
          - {
              label: 社交媒體,
              name: socialmedia,
              widget: list,
              fields:
                [
                  { label: 名字, name: name, widget: string },
                  { label: 鏈接, name: link, widget: string },
                  { label: QR, name: qr, widget: image },
                ],
            }
      - file: "src/pages/cn/services/index.md"
        label: "服務"
        name: "services"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "services-page",
            }
          - { label: "標題", name: "title", widget: "string" }
          - { label: "內容", name: "body", widget: "markdown" }
